name: Solar System Workflow

on: 
  # The pipeline automatically kicks off under two conditions:
  push:
    branches:
      - main
      - 'feature/*'
  # Pushes: Whenever code is pushed directly to the main branch or any branch starting with feature/ (like feature/login).
  pull_request:
    branches:
      - main
  # Pull Requests: Whenever a pull request is opened or updated targeting the main branch.

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs_version: [18, 20]
            operating_system: [ubuntu-latest, macos-latest]
            exclude:
              - nodejs_version: 18
                operating_system: macos-latest
        # It runs multiple test environments simultaneously. It tests your code on Ubuntu (using Node.js 18 and 20) and macOS (using Node.js 20). It specifically excludes testing Node 18 on macOS.
        
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS Version ${{matrix.nodejs_version}} 
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}
        
        - name: Cache NPM Dependencies
          uses: actions/cache@v5
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{hashFiles('package-lock.json')}}
        # It caches your node_modules folder. If your package-lock.json hasn't changed, it reuses the downloaded packages to drastically speed up the pipeline.
            
      
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-test-step
          run: npm test
        
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-Test-Result
            path: test-results.xml
        # It runs npm test. Even if the tests fail (if: always()), it takes the generated test-results.xml file and uploads it as an artifact so you can download and review the test failures from the GitHub Actions dashboard.
    
    code-coverage:
      name: Code Coverage
      # This job checks how much of your codebase is actually covered by your tests.
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Cache NPM Dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{hashFiles('package-lock.json')}}
      
      - name: Install Dependencies
        run: npm install
      
      - name: Check Code coverage
        continue-on-error: true
        run: npm run coverage
      # It runs npm run coverage, but uses continue-on-error: true. This means if your code coverage is lower than your required threshold, it will flag an error but won't stop the rest of the workflow from running.
      
      - name: Archive Test Result
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5
    
    docker:
        name: Containerization
        needs: [unit-testing, code-coverage]
        # The needs: [unit-testing, code-coverage] line is crucial. This job will not start until the first two jobs finish successfully. If your unit tests fail, it won't build the Docker image.
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v6
          
            # It logs into Docker Hub using your GitHub Secrets, builds the Docker container based on your project's Dockerfile, and pushes it to Docker Hub.
          - name: Login to Docker Hub
            uses: docker/login-action@v4
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Docker Image Build & Push 
            uses: docker/build-push-action@v7
            with:
              context: .
              push: true
              tags: ${{vars.DOCKER_USERNAME}}/solar-system:${{github.sha}}